server:
  port: 8888
spring:
  application:
    name: app-user
  jpa:
    show-sql: true
    properties:
      hibernate:
        type: trace
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    org:
      hibernate:
        type: trace


#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka/
#  instance:
#    prefer-ip-address: true



